require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - test_prof/rubocop

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - '**/*_spec.rb'

AllCops:
  NewCops: enable
  TargetRailsVersion: 7